# Generated by Django 5.1.1 on 2024-09-19 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Este campo precisa estar marcado para mostrar a pagina'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, default=None, null=True, unique=True)),
                ('excerpt', models.CharField(max_length=200)),
                ('is_published', models.BooleanField(default=False, help_text='Este campo precisa estar marcado para mostrar o Post')),
                ('content', models.TextField()),
                ('cover', models.ImageField(blank=True, default=True, upload_to='post/%Y/%m/')),
                ('cover_in_post_content', models.BooleanField(default=True, help_text='Deseja usar a imagem da capa dentro do post')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category')),
                ('tag', models.ManyToManyField(blank=True, default='', to='blog.tag')),
            ],
        ),
    ]
