# Generated by Django 5.1.1 on 2024-09-19 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_category_post_ategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='ategory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='update_by',
            new_name='updated_by',
        ),
    ]
