# Generated by Django 5.1.1 on 2024-09-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_profile_followers_count_delete_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follower',
            field=models.BooleanField(default=False),
        ),
    ]
